---
apiVersion: "v1"
kind: "Namespace"
metadata:
  name: "cluebatbot"
---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "cluebatbot"
  namespace: "cluebatbot"
  labels:
    app: "cluebatbot"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "cluebatbot"
  template:
    metadata:
      labels:
        app: "cluebatbot"
    spec:
      containers:
      - name: "cluebatbot"
        image: "gcr.io/craigskelton-com/cluebatbot:latest"
        env:
        - name: "REDIS_HOST"
          value: 'redis.dorkbot.svc.cluster.local:6379'
        - name: "CSLACK_DEBUG"
          value: 'true'
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: MY_POD_SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
---
apiVersion: "autoscaling/v1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "cluebatbot-hpa"
  namespace: "cluebatbot"
  labels:
    app: "cluebatbot"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "cluebatbot"
    apiVersion: "apps/v1beta1"
  minReplicas: 3
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80